# glew
xpProOption(glew)
set(GLEW_MSWVER 1.7.0)
set(GLEW_BLDVER 1.13.0)
########################################
function(patch_glew)
  set(mswVer ${GLEW_MSWVER})
  set(bldVer ${GLEW_BLDVER})
  if(NOT (XP_DEFAULT OR XP_PRO_GLEW OR XP_PRO_GLEW_${mswVer} OR XP_PRO_GLEW_${bldVer}))
    return()
  endif()
  if(XP_DEFAULT OR (XP_PRO_GLEW AND NOT (XP_PRO_GLEW_${mswVer} OR XP_PRO_GLEW_${bldVer})))
    if(XP_DEFAULT)
      set(TYPE INTERNAL)
    else()
      set(TYPE BOOL)
    endif()
    if(WIN32)
      set(XP_PRO_GLEW_${mswVer} ON CACHE ${TYPE} "include glew_${mswVer}" FORCE)
      set(XP_PRO_GLEW_${bldVer} OFF CACHE ${TYPE} "include glew_${bldVer}" FORCE)
    else()
      set(XP_PRO_GLEW_${mswVer} OFF CACHE ${TYPE} "include glew_${mswVer}" FORCE)
      set(XP_PRO_GLEW_${bldVer} ON CACHE ${TYPE} "include glew_${bldVer}" FORCE)
    endif()
  endif()
endfunction()
########################################
function(build_glew)
  set(mswVer ${GLEW_MSWVER})
  set(bldVer ${GLEW_BLDVER})
  if(NOT (XP_DEFAULT OR XP_PRO_GLEW_${mswVer} OR XP_PRO_GLEW_${bldVer}))
    return()
  endif()
  if(XP_PRO_GLEW_${mswVer})
    set(VER ${mswVer})
  elseif(XP_PRO_GLEW_${bldVer})
    set(VER ${bldVer})
  endif()
  configure_file(${PRO_DIR}/use/usexp-glew-config.cmake ${STAGE_DIR}/share/cmake/
    @ONLY NEWLINE_STYLE LF
    )
endfunction()
