function(recurseDirs base)
  if(EXISTS ${base} AND IS_DIRECTORY ${base})
    file(GLOB subdirs ${base}/*)
    foreach(subdir ${subdirs})
      recurseDirs(${subdir}/node_modules)
      list(APPEND dirList "${subdir}")
      set(dirList ${dirList} PARENT_SCOPE)
    endforeach()
  endif()
endfunction()

separate_arguments(dirs)
foreach(rootdir ${dirs})
  #message(STATUS "flatten: ${rootdir}")
  recurseDirs(${rootdir})
  foreach(d ${dirList})
    get_filename_component(l ${d} NAME)
    file(RENAME "${d}" "${rootdir}/${l}")
  endforeach()
endforeach()
