string(TOUPPER @NAME@ PRJ)
set(${PRJ}_VER "@VER@ [@PROJECT_NAME@]")
# http://docs.wxwidgets.org/trunk/page_libs.html
# TRICKY: reverse dependency order (base should be last)
set(wx_all_libs aui propgrid richtext adv gl html core net xml base)
include(${CMAKE_CURRENT_LIST_DIR}/@TARGETS_FILE@)
if(NOT DEFINED wx_libs)
  set(wx_libs ${wx_all_libs})
endif()
set(${PRJ}_LIBRARIES wx_libs)
list(TRANSFORM ${PRJ}_LIBRARIES PREPEND "wx::") # prepend NAMESPACE
set(reqVars ${PRJ}_VER ${PRJ}_LIBRARIES)
include(FindPackageHandleStandardArgs)
set(FPHSA_NAME_MISMATCHED TRUE) # find_package_handle_standard_args NAME_MISMATCHED (prefix usexp-)
find_package_handle_standard_args(@NAME@ REQUIRED_VARS ${reqVars})
mark_as_advanced(${reqVars})
