set(prj node)
# this file (-config) installed to share/cmake
get_filename_component(XP_ROOTDIR ${CMAKE_CURRENT_LIST_DIR}/../.. ABSOLUTE)
get_filename_component(XP_ROOTDIR ${XP_ROOTDIR} ABSOLUTE) # remove relative parts
include(${CMAKE_CURRENT_LIST_DIR}/xpfunmac.cmake)
if(MSVC)
  set(Node_LIB ${XP_ROOTDIR}/lib/node.lib)
  set(Node_EXE ${XP_ROOTDIR}/bin/node.exe)
  set(reqVars Node_LIB Node_EXE)
else()
  set(Node_LIB)
  set(Node_EXE ${XP_ROOTDIR}/bin/node)
  set(reqVars Node_EXE)
endif()
set(Npm_SCRIPT ${XP_ROOTDIR}/node_modules/npm/bin/npm-cli.js)
list(APPEND reqVars Npm_SCRIPT)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(${prj} REQUIRED_VARS ${reqVars})
mark_as_advanced(${reqVars})
